Add --use-plonky2-backend-experimental flag
The new flag switches to the PLONKY2 backend for proving and verifying
programs.

The added test generator illustrates how the flag can be used:

  nargo prove --use-plonky2-backend-experimental

At the moment, the expected behavior is that the following message is
reported for any program:

  Error: Backend does not support prove operation.

The following commits will change this.